Improve release workflow

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,27 +1,34 @@
 name: Release
+run-name: Release ${{ github.event.inputs.tag }}
 
 on:
     workflow_dispatch:
         inputs:
             tag:
-                description: "Tag (for example 0.1.5-experimental)"
+                description: "Tag, for example: v0.1.5-experimental"
                 required: true
                 type: string
 
 jobs:
-    release:
+    build:
+        name: Build
         runs-on: ubuntu-latest
-        outputs:
-            build: ${{ steps.build.outputs.build }}
         steps:
             - name: Validate tag
               run: |
-                  if [[ ! ${{ github.event.inputs.tag }} =~ ^[0-9]+\.[0-9]+\.[0-9]+(-experimental)?$ ]]; then
+                  if [[ ! ${{ github.event.inputs.tag }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+-experimental$ ]]; then
                       echo "Invalid tag format"
                       exit 1
                   fi
 
             - uses: actions/checkout@v4
+
+            - name: Ensure tag is available
+              run: |
+                  if ! git rev-parse ${{ github.event.inputs.tag }} >/dev/null 2>&1; then
+                      echo "::error::Tag \"${{ github.event.inputs.tag }}\" already exists, aborting"
+                      exit 1
+                  fi
 
             - name: Setup Node.js
               uses: actions/setup-node@v4
@@ -29,27 +36,61 @@ jobs:
                   node-version: "18"
 
             - name: Install dependencies
-              run: npm ci
+              run: yarn install --frozen-lockfile
 
-            - id: build
-              name: Build
+            - name: Build
               run: npm run build
 
-            - name: Copy build output to root
-              run: |
-                  cp -r packages/json-log-preview .
+            - name: Upload build artifact
+              uses: actions/upload-artifact@v3
+              with:
+                  name: build
+                  path: packages/json-log-preview/
+
+    release:
+        name: Release
+        needs: build
+        runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v4
+
+            - name: Create branch `release/latest-experimental`
+              run: git switch --orphan release/latest-experimental
+
+            - name: Download build arficat
+              uses: actions/download-artifact@v3
+              with:
+                  name: build
+
+            - name: Display structure of downloaded files
+              run: ls -R
 
             - name: Git add
-              run: git add package.json && git add dist
+              run: git add .
 
-            - name: Create branch release-experimental
-              run: git branch -D release/latest-experimental git switch --orphan release/latest-experimental
+            - name: Git config
+              run: |
+                  git config user.name "GitHub Actions"
+                  git config user.email "6334521+aarokorhonen@users.noreply.github.com"
 
             - name: Git commit
-              run: git commit -m "Release v${{ github.event.inputs.tag }}"
+              run: git commit -m "Release ${{ github.event.inputs.tag }}"
 
             - name: Git tag
-              run: git tag -a ${{ github.event.inputs.tag }} -m "Release v${{ github.event.inputs.tag }}"
+              run: git tag -a ${{ github.event.inputs.tag }} -m "Release ${{ github.event.inputs.tag }}"
 
             - name: Git push tag
               run: git push origin ${{ github.event.inputs.tag }}
+
+            - name: Git push branch
+              run: git push origin release/latest-experimental --force-with-lease
+
+            - name: Release on GitHub
+              uses: softprops/action-gh-release@v1
+              with:
+                  files: "*"
+                  tag_name: ${{ github.event.inputs.tag }}
+                  draft: true
+                  prerelease: true
+                  body: |
+                      This is an experimental release.
